Repository AY2223S1-CS2103T-W17-4/tp, pull requests merged in 2022-10, with the labels that each got.

#35 Adding docs
  README.md
  docs/UserGuide.md
Labels: documentation

#25 Modify delete command
  src/main/java/seedu/address/commons/core/index/Indexes.java
  src/main/java/seedu/address/commons/exceptions/IllegalIndexException.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Story, priority.High

#26 Modify add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/ApplicationProcess.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Position.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/Website.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#38 Modify list command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ComparableCategoryParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/ApplicationProcess.java
  src/main/java/seedu/address/model/person/ComparableCategory.java
  src/main/java/seedu/address/model/person/ComparableModel.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Position.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Story, priority.High

#39 Modify find command
  src/main/java/seedu/address/commons/core/keyword/Keyword.java
  src/main/java/seedu/address/commons/core/keyword/KeywordList.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindableCategoryParser.java
  src/main/java/seedu/address/logic/parser/exceptions/InvalidCategoryException.java
  src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/FindableCategory.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.High, type.task

#40 Fix issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/keyword/Keyword.java
  src/main/java/seedu/address/commons/core/keyword/KeywordList.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindableCategoryParser.java
  src/main/java/seedu/address/logic/parser/exceptions/InvalidCategoryException.java
  src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/FindableCategory.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: bug, documentation, priority.High, type.task

#51 Add find command tests
  src/main/java/seedu/address/commons/core/keyword/Keyword.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/exceptions/InvalidCategoryException.java
  src/test/java/seedu/address/commons/core/keyword/KeywordListTest.java
  src/test/java/seedu/address/commons/core/keyword/KeywordTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindableCategoryParserTest.java
Labels: priority.High

#65 Add tests for Indexes class
  src/test/java/seedu/phu/commons/core/index/IndexesTest.java
Labels: type.Testing

#66 Update `edit` command documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/sugiyem.md
Labels: documentation

#68 Add documentation for `add` command
  docs/UserGuide.md
  docs/images/rachel-ag.png
  docs/team/rachel-ag.md
  src/main/java/seedu/phu/model/internship/Date.java
  src/main/java/seedu/phu/model/internship/Internship.java
  src/main/java/seedu/phu/model/internship/Name.java
  src/main/java/seedu/phu/model/internship/Phone.java
Labels: documentation

#69 Bug fixes for `view` command, improve documentation and add test cases
  docs/UserGuide.md
  docs/team/aarontangr.md
  src/main/java/seedu/phu/logic/commands/ViewCommand.java
  src/main/java/seedu/phu/logic/parser/ViewCommandParser.java
  src/main/java/seedu/phu/model/Model.java
  src/main/java/seedu/phu/model/ModelManager.java
  src/main/java/seedu/phu/model/internship/ExactMatchPredicate.java
  src/test/java/seedu/phu/logic/commands/AddCommandTest.java
  src/test/java/seedu/phu/logic/commands/ViewCommandTest.java
  src/test/java/seedu/phu/logic/parser/ViewCommandParserTest.java
Labels: documentation, priority.High

#70 Updated User Guide for `list` command and Justin's PPP
  README.md
  docs/UserGuide.md
  docs/images/justins00.png
  docs/team/justins00.md
  src/main/java/seedu/phu/logic/commands/ListCommand.java
Labels: documentation

#71 Update Docs and PPP
  docs/DeveloperGuide.md
  docs/team/elben85.md
Labels: documentation

#78 Add view UI box
  docs/team/aarontangr.md
  src/main/java/seedu/phu/commons/core/GuiSettings.java
  src/main/java/seedu/phu/logic/Logic.java
  src/main/java/seedu/phu/logic/LogicManager.java
  src/main/java/seedu/phu/logic/commands/ViewCommand.java
  src/main/java/seedu/phu/model/Model.java
  src/main/java/seedu/phu/model/ModelManager.java
  src/main/java/seedu/phu/ui/HelpWindow.java
  src/main/java/seedu/phu/ui/MainWindow.java
  src/main/java/seedu/phu/ui/UiManager.java
  src/main/java/seedu/phu/ui/ViewCommandCard.java
  src/main/java/seedu/phu/ui/ViewCommandPanel.java
  src/main/resources/view/InternshipListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ViewCommandCard.fxml
  src/main/resources/view/ViewCommandPanel.fxml
  src/test/java/seedu/phu/logic/commands/AddCommandTest.java
  src/test/java/seedu/phu/logic/commands/ViewCommandTest.java
  src/test/java/seedu/phu/testutil/TypicalIndexes.java
Labels: enhancement

#76 Add `undo` and `redo` command
  src/main/java/seedu/phu/logic/LogicManager.java
  src/main/java/seedu/phu/logic/commands/AddCommand.java
  src/main/java/seedu/phu/logic/commands/ClearCommand.java
  src/main/java/seedu/phu/logic/commands/Command.java
  src/main/java/seedu/phu/logic/commands/CommandHistory.java
  src/main/java/seedu/phu/logic/commands/DeleteCommand.java
  src/main/java/seedu/phu/logic/commands/EditCommand.java
  src/main/java/seedu/phu/logic/commands/ExitCommand.java
  src/main/java/seedu/phu/logic/commands/FindCommand.java
  src/main/java/seedu/phu/logic/commands/HelpCommand.java
  src/main/java/seedu/phu/logic/commands/ListCommand.java
  src/main/java/seedu/phu/logic/commands/RedoCommand.java
  src/main/java/seedu/phu/logic/commands/UndoCommand.java
  src/main/java/seedu/phu/logic/commands/ViewCommand.java
  src/main/java/seedu/phu/logic/parser/InternshipBookParser.java
  src/main/java/seedu/phu/model/Model.java
  src/main/java/seedu/phu/model/ModelManager.java
  src/main/java/seedu/phu/model/VersionedInternshipBook.java
  src/test/java/seedu/phu/logic/LogicManagerTest.java
  src/test/java/seedu/phu/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/phu/logic/commands/AddCommandTest.java
  src/test/java/seedu/phu/logic/commands/ClearCommandTest.java
  src/test/java/seedu/phu/logic/commands/CommandHistoryTest.java
  src/test/java/seedu/phu/logic/commands/CommandTestUtil.java
  src/test/java/seedu/phu/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/phu/logic/commands/EditCommandTest.java
  src/test/java/seedu/phu/logic/commands/ExitCommandTest.java
  src/test/java/seedu/phu/logic/commands/FindCommandTest.java
  src/test/java/seedu/phu/logic/commands/HelpCommandTest.java
  src/test/java/seedu/phu/logic/commands/ListCommandTest.java
  src/test/java/seedu/phu/logic/commands/RedoCommandTest.java
  src/test/java/seedu/phu/logic/commands/UndoCommandTest.java
  src/test/java/seedu/phu/logic/commands/ViewCommandTest.java
  src/test/java/seedu/phu/logic/parser/InternshipBookParserTest.java
  src/test/java/seedu/phu/model/ModelManagerTest.java
  src/test/java/seedu/phu/model/VersionedInternshipBookTest.java
Labels: priority.High

#80 Update DG For Find Command
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: documentation

#83 Fix resizing of whole window
  src/main/java/seedu/phu/ui/UiManager.java
  src/main/resources/view/InternshipListCard.fxml
  src/main/resources/view/InternshipListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ViewCommandPanel.fxml
  src/test/java/seedu/phu/logic/commands/ViewCommandTest.java
Labels: enhancement

#84 Add hyperlink to website in view UI box
  src/main/java/seedu/phu/commons/core/GuiSettings.java
  src/main/java/seedu/phu/ui/ViewCommandCard.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ViewCommandCard.fxml
Labels: enhancement

#88 Update DG for `list` command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/ListSequenceDiagram.png
  src/main/java/seedu/phu/MainApp.java
Labels: documentation

#90 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#91 Update test case names
  src/test/data/JsonInternshipBookStorageTest/invalidAndValidInternshipInternshipBook.json
  src/test/data/JsonSerializableInternshipBookTest/duplicateInternshipInternshipBook.json
  src/test/data/JsonSerializableInternshipBookTest/typicalInternshipInternshipBook.json
  src/test/java/seedu/phu/commons/core/index/IndexesTest.java
  src/test/java/seedu/phu/logic/LogicManagerTest.java
  src/test/java/seedu/phu/logic/commands/AddCommandTest.java
  src/test/java/seedu/phu/logic/commands/CommandTestUtil.java
  src/test/java/seedu/phu/logic/commands/EditCommandTest.java
  src/test/java/seedu/phu/logic/commands/EditInternshipDescriptorTest.java
  src/test/java/seedu/phu/logic/commands/FindCommandTest.java
  src/test/java/seedu/phu/logic/commands/ListCommandTest.java
  src/test/java/seedu/phu/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/phu/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/phu/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/phu/logic/parser/ParserUtilTest.java
  src/test/java/seedu/phu/model/InternshipBookTest.java
  src/test/java/seedu/phu/model/ModelManagerTest.java
  src/test/java/seedu/phu/model/VersionedInternshipBookTest.java
  src/test/java/seedu/phu/model/internship/InternshipTest.java
  src/test/java/seedu/phu/model/internship/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/phu/model/internship/UniqueInternshipListTest.java
  src/test/java/seedu/phu/model/internship/WebsiteTest.java
  src/test/java/seedu/phu/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/phu/storage/JsonInternshipBookStorageTest.java
  src/test/java/seedu/phu/testutil/InternshipBuilder.java
  src/test/java/seedu/phu/testutil/TypicalInternships.java
Labels: documentation

#95 Add statistics
  docs/team/elben85.md
  src/main/java/seedu/phu/model/internship/ApplicationProcess.java
  src/main/java/seedu/phu/model/internship/Statistic.java
  src/main/java/seedu/phu/ui/MainWindow.java
  src/main/java/seedu/phu/ui/StackedBarPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StackedBarPanel.fxml
Labels: enhancement, type.Story

#97 Fix UML Sequence Diagram
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: bug, documentation

#100 Remove status bar, set remark text to wrap
  src/main/java/seedu/phu/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ViewCommandCard.fxml
Labels: bug, enhancement

#102 Modify `help` command UI
  src/main/java/seedu/phu/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: enhancement

#110 Add undo and redo to command summary
  src/main/java/seedu/phu/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: documentation

#112 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: documentation

#121 Improve test coverage
  README.md
  build.gradle
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/test/java/seedu/phu/commons/core/ConfigTest.java
  src/test/java/seedu/phu/commons/core/GuiSettingsTest.java
  src/test/java/seedu/phu/model/UserPrefsTest.java
  src/test/java/seedu/phu/model/util/SampleDataUtilTest.java
Labels: type.Testing

#122 Add more exception handling for View, Copy
  src/main/java/seedu/phu/logic/parser/CopyCommandParser.java
  src/main/java/seedu/phu/logic/parser/ViewCommandParser.java
  src/test/java/seedu/phu/logic/parser/CopyCommandParserTest.java
  src/test/java/seedu/phu/logic/parser/ViewCommandParserTest.java
Labels: bug, type.Testing

#93 Add `get-previous-command` feature
  src/main/java/seedu/phu/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: enhancement

#128 Update UserGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#130 UI refinements
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StackedBarPanel.fxml
Labels: bug, enhancement

#135 Update UG, DG for `view` and `copy`
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#138 Update User Guide
  docs/UserGuide.md
  src/main/java/seedu/phu/ui/HelpWindow.java
Labels: documentation

#141 Help window refinements
  docs/UserGuide.md
  docs/images/AfterAddCommand.png
  docs/images/BeforeAddCommand.png
  docs/images/helpMessage.png
  src/main/java/seedu/phu/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: documentation, enhancement

#137 Update UG & DG For Statistics and Add Prefix Summary
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BarChartSequenceDiagram.puml
  docs/images/BarChart.png
  docs/images/BarChartSequenceDiagram.png
  src/main/java/seedu/phu/model/internship/Statistic.java
  src/main/java/seedu/phu/ui/StackedBarPanel.java
Labels: documentation, priority.High

#142 `view` and `copy` sequence diagrams
  docs/DeveloperGuide.md
  docs/diagrams/BarChartSequenceDiagram.puml
  docs/diagrams/CopySequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/BarChartSequenceDiagram.png
  docs/images/CopySequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/ViewSequenceDiagram.png
Labels: documentation

#144 Update UI component in DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/phu/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: documentation, priority.High

#133 Update DG: `Logic` and `VersionedInternshipBook`
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
Labels: documentation

#153 DG: Add more details to `delete` and `edit` implementation
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram2.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram2.png
  docs/images/EditSequenceDiagram.png
Labels: documentation

#166 Fix issues
  docs/DeveloperGuide.md
  src/main/java/seedu/phu/logic/commands/AddCommand.java
  src/main/java/seedu/phu/ui/HelpWindow.java
Labels: bug

#167 Update UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/BarChart.png
  docs/images/icon.png
Labels: documentation

#168 Update UG: Reorder steps in QuickStart, update tip box for `list` and `find`
  docs/UserGuide.md
Labels: documentation

#209 Fix `delete` command bug
  src/main/java/seedu/phu/commons/core/index/Index.java
  src/test/java/seedu/phu/commons/core/index/IndexTest.java
  src/test/java/seedu/phu/commons/core/index/IndexesTest.java
Labels: bug

#178 Update `edit` details in UG
  docs/UserGuide.md
Labels: bug, documentation

#176 Change date validation to strict
  src/main/java/seedu/phu/model/internship/Date.java
  src/test/java/seedu/phu/model/internship/DateTest.java
Labels: bug

#208 UG: Fix short-form for company_name
  docs/UserGuide.md
Labels: bug, documentation

#196 Add some UI tests
  build.gradle
  src/test/java/seedu/phu/ui/CommandBoxTest.java
  src/test/java/seedu/phu/ui/GuiUnitTest.java
  src/test/java/seedu/phu/ui/InternshipCardTest.java
  src/test/java/seedu/phu/ui/ResultDisplayTest.java
  src/test/java/seedu/phu/ui/UiPartExtension.java
Labels: type.Testing

#212 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/CopySequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram2.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/CopySequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteSequenceDiagram2.png
  docs/images/EditSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/ViewSequenceDiagram.png
Labels: documentation

#218 PE-D feedback fixes
  src/main/java/seedu/phu/model/internship/Internship.java
  src/main/java/seedu/phu/ui/InternshipCard.java
  src/main/java/seedu/phu/ui/ViewCommandCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ViewCommandCard.fxml
Labels: bug

#214 Fix phone number validation
  src/main/java/seedu/phu/model/internship/Phone.java
  src/test/java/seedu/phu/logic/parser/ParserUtilTest.java
  src/test/java/seedu/phu/model/internship/PhoneTest.java
  src/test/java/seedu/phu/storage/JsonAdaptedInternshipTest.java
Labels: bug

#220 PE-D fixes
  src/main/java/seedu/phu/logic/parser/ParserUtil.java
  src/main/java/seedu/phu/model/internship/Internship.java
  src/main/java/seedu/phu/model/tag/Tag.java
  src/test/java/seedu/phu/logic/commands/CommandTestUtil.java
  src/test/java/seedu/phu/logic/parser/AddCommandParserTest.java
Labels: bug

#221 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#217 Fix email validation: must include at least 2 domain label
  src/main/java/seedu/phu/model/internship/Email.java
  src/test/java/seedu/phu/model/internship/EmailTest.java
Labels: bug

#223 Add application process validation
  docs/UserGuide.md
  src/main/java/seedu/phu/commons/core/keyword/Keyword.java
  src/main/java/seedu/phu/commons/core/keyword/KeywordList.java
  src/main/java/seedu/phu/logic/parser/FindCommandParser.java
  src/test/java/seedu/phu/logic/parser/FindCommandParserTest.java
Labels: bug
